{{- if eq (include "hasGrafana" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  admin-user: {{ .Values.global.grafana.secrets.adminUser | quote }}
  admin-password: {{ .Values.global.grafana.secrets.adminPassword | quote }}
{{- end }}
