{{- if eq .Values.appStack.observability.logging.stack "loki" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ lower $.Release.Name }}-promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  config.yml: |
{{ .Files.Get "files/promtail/config.yml.tpl" | indent 4 }}
{{- end }}
