management:
  endpoints:
    web:
      exposure:
        # Spring Cloud Gateway: gateway,refresh,routes
        # curl -X GET http://<gateway-host>:<port>/actuator/gateway/routes
        # curl -X POST http://<gateway-host>:<port>/actuator/gateway/refresh
        include: health,info,prometheus,gateway,refresh,routes
  endpoint:
    gateway:
      access: unrestricted

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: RequestRateLimiter
              args:
                rate-limiter: "#{@userRateLimiter}"
                key-resolver: "#{@userKeyResolver}"
          httpclient:
            connect-timeout: 30000  # Connection timeout in milliseconds
            response-timeout: 5m # Response timeout in ISO-8601 format or duration
            pool:
              max-idle-time: 45m # Allow connections to stay idle longer for SSE/WebSocket
          routes:
            # User service
            - id: user-service-admin
              uri: ${USER_SERVICE_URI:lb://user-service}
              predicates:
                - Path=/api/user-svc/admin/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - TokenValidation
                - Authorization=ADMIN
                - TokenRelay
                - RewritePath=/api/user-svc/admin/(?<segment>.*), /api/admin/${segment}
            - id: user-service
              uri: ${USER_SERVICE_URI:lb://user-service}
              predicates:
                - Path=/api/user-svc/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - TokenValidation
                - TokenRelay
                - RewritePath=/api/user-svc/(?<segment>.*), /api/${segment}
            - id: user-service-auth
              uri: ${USER_SERVICE_URI:lb://user-service}
              predicates:
                - Path=/api/user-svc/auth/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - TokenValidation
                - TokenRelay
                - RewritePath=/api/user-svc/auth/(?<segment>.*), /api/auth/${segment}
            - id: user-service-api-docs
              uri: ${USER_SERVICE_URI:lb://user-service}
              predicates:
                - Path=/api-docs/user-svc
              filters:
                - RewritePath=/api-docs/user-svc, /api-docs
            # Product service
            - id: product-service
              uri: ${PRODUCT_SERVICE_URI:lb://product-service}
              predicates:
                - Path=/api/product-svc/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - RewritePath=/api/product-svc/(?<segment>.*), /api/${segment}
            - id: product-service-admin
              uri: ${PRODUCT_SERVICE_URI:lb://product-service}
              predicates:
                - Path=/api/product-svc/admin/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - TokenValidation
                - Authorization=ADMIN
                - TokenRelay
                - RewritePath=/api/product-svc/admin/(?<segment>.*), /api/admin/${segment}
            - id: product-service-api-docs
              uri: ${PRODUCT_SERVICE_URI:lb://product-service}
              predicates:
                - Path=/api-docs/product-svc
              filters:
                - RewritePath=/api-docs/product-svc, /api-docs
            # Order service
            - id: order-service
              uri: ${ORDER_SERVICE_URI:lb://order-service}
              predicates:
                - Path=/api/order-svc/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - TokenValidation
                - TokenRelay
                - RewritePath=/api/order-svc/(?<segment>.*), /api/${segment}
            - id: order-service-admin
              uri: ${ORDER_SERVICE_URI:lb://order-service}
              predicates:
                - Path=/api/order-svc/admin/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - TokenValidation
                - Authorization=ADMIN
                - TokenRelay
                - RewritePath=/api/order-svc/admin/(?<segment>.*), /api/admin/${segment}
            - id: order-service-sse
              uri: ${ORDER_SERVICE_URI:lb://order-service}
              predicates:
                - Path=/order-svc/sse/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - RewritePath=/order-svc/sse/(?<segment>.*), /notification/sse/${segment}
            - id: order-service-websocket
              uri: ${ORDER_SERVICE_URI:lb://order-service}
              predicates:
                - Path=/order-svc/ws/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - RewritePath=/order-svc/ws/(?<segment>.*), /notification/ws/${segment}
            - id: order-service-api-docs
              uri: ${ORDER_SERVICE_URI:lb://order-service}
              predicates:
                - Path=/api-docs/order-svc
              filters:
                - RewritePath=/api-docs/order-svc, /api-docs
            # Payment service
            - id: payment-service
              uri: ${PAYMENT_SERVICE_URI:lb://payment-service}
              predicates:
                - Path=/api/payment-svc/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
                - RewritePath=/api/payment-svc/(?<segment>.*), /api/${segment}
            - id: payment-service-webhook
              uri: ${PAYMENT_SERVICE_URI:lb://payment-service}
              predicates:
                - Path=/api/payment-svc/webhook/**
              filters:
                - RewritePath=/api/payment-svc/webhook/(?<segment>.*), /api/webhook/${segment}
            - id: payment-service-api-docs
              uri: ${PAYMENT_SERVICE_URI:lb://payment-service}
              predicates:
                - Path=/api-docs/payment-svc
              filters:
                - RewritePath=/api-docs/payment-svc, /api-docs
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
  reactor:
    context-propagation: auto # Enable tracing
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}

app:
  api-gateway:
    auth-server: spring-security-jwt

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /api-docs/user-svc
      - name: Product Service
        url: /api-docs/product-svc
      - name: Order Service
        url: /api-docs/order-svc
    default-models-expand-depth: -1 # Hide Schemas section
