app:
  messaging:
    sns:
      sns-topic-arn:
        user-event: ${SNS_TOPIC_ARN_USER_EVENT}
        product-event: ${SNS_TOPIC_ARN_PRODUCT_EVENT}
        order-event: ${SNS_TOPIC_ARN_ORDER_EVENT}
      sqs-queue-url:
        # Product service
        product-svc-order-event: ${SQS_QUEUE_URL_PRODUCT_SVC_ORDER_EVENT}
        # Order service
        order-svc-order-event: ${SQS_QUEUE_URL_ORDER_SVC_ORDER_EVENT}
        # Payment service
        payment-svc-order-event: ${SQS_QUEUE_URL_PAYMENT_SVC_ORDER_EVENT}
      visibility-timeout: 30
      wait-time-seconds: 20
      batch-size: 10
