app:
  messaging:
    sns:
      sns-topic-arn:
        # Order service
        saga.checkout.command.order: ${SNS_TOPIC_ARN_SAGA_CHECKOUT_COMMAND_ORDER}
        saga.checkout.compensation.order: ${SNS_TOPIC_ARN_SAGA_CHECKOUT_COMPENSATION_ORDER}
        saga.checkout.commandreply: ${SNS_TOPIC_ARN_SAGA_CHECKOUT_COMMANDREPLY}
        saga.checkout.compensationreply: ${SNS_TOPIC_ARN_SAGA_CHECKOUT_COMPENSATIONREPLY}
        # Payment service
        saga.checkout.command.payment: ${SNS_TOPIC_ARN_SAGA_CHECKOUT_COMMAND_PAYMENT}
        saga.checkout.compensation.payment: ${SNS_TOPIC_ARN_SAGA_CHECKOUT_COMPENSATION_PAYMENT}
        # Product service
        product_events: ${SNS_TOPIC_ARN_PRODUCT_EVENTS}
        saga.checkout.command.product: ${SNS_TOPIC_ARN_SAGA_CHECKOUT_COMMAND_PRODUCT}
        saga.checkout.compensation.product: ${SNS_TOPIC_ARN_SAGA_CHECKOUT_COMPENSATION_PRODUCT}
        # User service
        user_events: ${SNS_TOPIC_ARN_USER_EVENTS}
      sqs-queue-url:
        # Order service
        saga.checkout.command.order: ${SNS_QUEUE_URL_SAGA_CHECKOUT_COMMAND_ORDER}
        saga.checkout.compensation.order: ${SNS_QUEUE_URL_SAGA_CHECKOUT_COMPENSATION_ORDER}
        saga.checkout.commandreply: ${SNS_QUEUE_URL_SAGA_CHECKOUT_COMMANDREPLY}
        saga.checkout.compensationreply: ${SNS_QUEUE_URL_SAGA_CHECKOUT_COMPENSATIONREPLY}
        # Payment service
        saga.checkout.command.payment: ${SNS_QUEUE_URL_SAGA_CHECKOUT_COMMAND_PAYMENT}
        saga.checkout.compensation.payment: ${SNS_QUEUE_URL_SAGA_CHECKOUT_COMPENSATION_PAYMENT}
        # Product service
        saga.checkout.command.product: ${SNS_QUEUE_URL_SAGA_CHECKOUT_COMMAND_PRODUCT}
        saga.checkout.compensation.product: ${SNS_QUEUE_URL_SAGA_CHECKOUT_COMPENSATION_PRODUCT}
      visibility-timeout: 30
      wait-time-seconds: 20
      batch-size: 10
