plugins {
    id 'java-library'
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'com.google.protobuf' version '0.9.5'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.grpc:grpc-services'
}

sourceSets {
    main {
        java {
            srcDirs 'build/generated/source/proto/main/grpc'
            srcDirs 'build/generated/source/proto/main/java'
        }
    }
}

dependencyManagement {
  imports {
    mavenBom "org.springframework.grpc:spring-grpc-dependencies:${springGrpcVersion}"
  }
}

protobuf {
  protoc {
    artifact = 'com.google.protobuf:protoc'
  }
  plugins {
    grpc {
      artifact = 'io.grpc:protoc-gen-grpc-java'
    }
  }
  generateProtoTasks {
    all()*.plugins {
      grpc {
        option '@generated=omit'
      }
    }
  }
}

dependencyManagement {
    imports {
        mavenBom 'com.google.protobuf:protobuf-bom:3.25.1'
    }
}
