plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Datasource
    switch (rootProject.ext.appStack['datasource']) {
        case 'mysql':
            api project(':services.inventory.datasource.mysql')
            break
        case 'postgres':
            api project(':services.inventory.datasource.postgres')
            break
        default:
            throw new IllegalArgumentException("Unsupported datasource: ${rootProject.ext.appStack['datasource']}")
    }

    // KV store
    switch (rootProject.ext.appStack['kv-store']) {
        case 'redis':
            api project(':libs.kv-store.redis')
            break
        default:
            throw new IllegalArgumentException("Unsupported kv-store: ${rootProject.ext.appStack['kv-store']}")
    }
    
    // Messaging
    switch (rootProject.ext.appStack['messaging']) {
        case 'kafka':
            api project(':services.inventory.messaging.kafka')
            break
        case 'rabbitmq':
            api project(':services.inventory.messaging.rabbitmq')
            break
        default:
            throw new IllegalArgumentException("Unsupported messaging: ${rootProject.ext.appStack['messaging']}")
    }
    
    // Migration
    switch (rootProject.ext.appStack['migration']) {
        case 'flyway':
            switch (rootProject.ext.appStack['datasource']) {
                case 'mysql':
                    api project(':services.inventory.migration.flyway.mysql')
                    break
                case 'postgres':
                    api project(':services.inventory.migration.flyway.postgres')
                    break
                default:
                    throw new IllegalArgumentException("Unsupported datasource: ${rootProject.ext.appStack['datasource']}")
            }
            break
        default:
            throw new IllegalArgumentException("Unsupported migration: ${rootProject.ext.appStack['migration']}")
    }
    
    // Observability
    switch (rootProject.ext.appStack['observability.logging.framework']) {
        case 'logback':
            api project(':libs.observability.logging.logback')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.logging.framework: ${rootProject.ext.appStack['observability.logging.framework']}")
    }
    switch (rootProject.ext.appStack['observability.metrics']) {
        case 'none':
            break;
        case 'prometheus':
            api project(':libs.observability.metrics.prometheus')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.metrics: ${rootProject.ext.appStack['observability.metrics']}")
    }
    switch (rootProject.ext.appStack['observability.tracing']) {
        case 'none':
            break
        case 'zipkin':
            api project(':libs.observability.tracing.zipkin')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.tracing: ${rootProject.ext.appStack['observability.tracing']}")
    }
    
    // Outbox
    api project(':libs.outbox')

    // Persistence
    switch (rootProject.ext.appStack.persistence) {
        case 'jpa':
            api project(':services.inventory.persistence.jpa')
            break
        default:
            throw new IllegalArgumentException("Unsupported persistence: ${rootProject.ext.appStack.persistence}")
    }

    // Saga
    api project(':libs.saga')

    // Sequence generator
    api project(':libs.sequence-generator')

    // Service discovery
    switch (rootProject.ext.appStack['service-discovery']) {
        case 'none':
            break
        case 'eureka':
            api project(':libs.discovery-client.eureka')
            break
        case 'kubernetes':
            api project(':libs.discovery-client.kubernetes')
            break
        default:
            throw new IllegalArgumentException("Unsupported service-discovery: ${rootProject.ext.appStack['service-discovery']}")
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}


idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
