{{- if eq .Values.appStack.datasource "postgres" }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  user: {{ .Values.postgres.secrets.user }}
  password: {{ .Values.postgres.secrets.password }}
{{- end }}
