{{- if eq .Values.appStack.datasource "postgres" }}
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.ports.postgres }}
      targetPort: postgres
{{- end }}
