{{- if eq .Values.appStack.observability.metrics "prometheus" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ lower $.Release.Name }}-prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
  ports:
    - name: http
      port: {{ .Values.prometheus.service.ports.http }}
      targetPort: http
{{- end }}
