apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-local-config
  labels:
    app.kubernetes.io/name: atlas
    app.kubernetes.io/instance: atlas-local
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: config
data:
  SPRING_PROFILES_ACTIVE: "local"
  LOG_LEVEL: "DEBUG"
