grpc:
  client:
    payment-service:
      enableKeepAlive: 'true'
      negotiationType: plaintext
      keepAliveWithoutCalls: 'true'
      address: ${API_CLIENT_GRPC_PAYMENT_SERVICE_ADDRESS:'static://127.0.0.1:50054'}
