// =================================================================================================
// Framework
// =================================================================================================

include(':framework')
project(':framework').projectDir = file('framework')

// =================================================================================================
// Domain
// =================================================================================================

include(':domain.auth')
project(':domain.auth').projectDir = file('domain/auth-domain')

include(':domain.notification')
project(':domain.notification').projectDir = file('domain/notification-domain')

include(':domain.order')
project(':domain.order').projectDir = file('domain/order-domain')
include(':domain.order.shared')
project(':domain.order.shared').projectDir = file('domain/order-domain-shared')

include(':domain.payment')
project(':domain.payment').projectDir = file('domain/payment-domain')
include(':domain.payment.shared')
project(':domain.payment.shared').projectDir = file('domain/payment-domain-shared')

include(':domain.product')
project(':domain.product').projectDir = file('domain/product-domain')
include(':domain.product.shared')
project(':domain.product.shared').projectDir = file('domain/product-domain-shared')

include(':domain.user')
project(':domain.user').projectDir = file('domain/user-domain')
include(':domain.user.shared')
project(':domain.user.shared').projectDir = file('domain/user-domain-shared')

// =================================================================================================
// Infrastructure
// =================================================================================================

// API client
include(':infrastructure.api-client.grpc.netdevh')
project(':infrastructure.api-client.grpc.netdevh').projectDir = file('infrastructure/api-client/api-client-grpc-netdevh')
include(':infrastructure.api-client.rest.apachehttpclient')
project(':infrastructure.api-client.rest.apachehttpclient').projectDir = file('infrastructure/api-client/api-client-rest-apachehttpclient')
include(':infrastructure.api-client.rest.feign')
project(':infrastructure.api-client.rest.feign').projectDir = file('infrastructure/api-client/api-client-rest-feign')
include(':infrastructure.api-client.rest.model')
project(':infrastructure.api-client.rest.model').projectDir = file('infrastructure/api-client/api-client-rest-model')
include(':infrastructure.api-client.rest.restclient')
project(':infrastructure.api-client.rest.restclient').projectDir = file('infrastructure/api-client/api-client-rest-restclient')
include(':infrastructure.api-client.rest.resttemplate')
project(':infrastructure.api-client.rest.resttemplate').projectDir = file('infrastructure/api-client/api-client-rest-resttemplate')

// API server

// API server::gRPC

// API server::gRPC::Protobuf
include(':infrastructure.api-server.grpc.protobuf')
project(':infrastructure.api-server.grpc.protobuf').projectDir = file('infrastructure/api-server/grpc/protobuf')

// API server::gRPC::netdevh
include(':infrastructure.api-server.grpc.netdevh.core')
project(':infrastructure.api-server.grpc.netdevh.core').projectDir = file('infrastructure/api-server/grpc/netdevh/api-server-grpc-netdevh-core')
include(':infrastructure.api-server.grpc.netdevh.impl.product')
project(':infrastructure.api-server.grpc.netdevh.impl.product').projectDir = file('infrastructure/api-server/grpc/netdevh/api-server-grpc-netdevh-impl-product')
include(':infrastructure.api-server.grpc.netdevh.impl.user')
project(':infrastructure.api-server.grpc.netdevh.impl.user').projectDir = file('infrastructure/api-server/grpc/netdevh/api-server-grpc-netdevh-impl-user')

// API server::REST
include(':infrastructure.api-server.rest.core')
project(':infrastructure.api-server.rest.core').projectDir = file('infrastructure/api-server/rest/api-server-rest-core')
include(':infrastructure.api-server.rest.impl.auth')
project(':infrastructure.api-server.rest.impl.auth').projectDir = file('infrastructure/api-server/rest/api-server-rest-impl-auth')
include(':infrastructure.api-server.rest.impl.notification')
project(':infrastructure.api-server.rest.impl.notification').projectDir = file('infrastructure/api-server/rest/api-server-rest-impl-notification')
include(':infrastructure.api-server.rest.impl.order')
project(':infrastructure.api-server.rest.impl.order').projectDir = file('infrastructure/api-server/rest/api-server-rest-impl-order')
include(':infrastructure.api-server.rest.impl.payment')
project(':infrastructure.api-server.rest.impl.payment').projectDir = file('infrastructure/api-server/rest/api-server-rest-impl-payment')
include(':infrastructure.api-server.rest.impl.product')
project(':infrastructure.api-server.rest.impl.product').projectDir = file('infrastructure/api-server/rest/api-server-rest-impl-product')
include(':infrastructure.api-server.rest.impl.user')
project(':infrastructure.api-server.rest.impl.user').projectDir = file('infrastructure/api-server/rest/api-server-rest-impl-user')

// Auth

// Auth::Keycloak
include(':infrastructure.auth.keycloak')
project(':infrastructure.auth.keycloak').projectDir = file('infrastructure/auth/auth-keycloak')

// Datasource

// Datasource::MySQL
include(':infrastructure.datasource.mysql.core')
project(':infrastructure.datasource.mysql.core').projectDir = file('infrastructure/datasource/mysql/datasource-mysql-core')
include(':infrastructure.datasource.mysql.impl.auth')
project(':infrastructure.datasource.mysql.impl.auth').projectDir = file('infrastructure/datasource/mysql/datasource-mysql-impl-auth')
include(':infrastructure.datasource.mysql.impl.notification')
project(':infrastructure.datasource.mysql.impl.notification').projectDir = file('infrastructure/datasource/mysql/datasource-mysql-impl-notification')
include(':infrastructure.datasource.mysql.impl.order')
project(':infrastructure.datasource.mysql.impl.order').projectDir = file('infrastructure/datasource/mysql/datasource-mysql-impl-order')
include(':infrastructure.datasource.mysql.impl.payment')
project(':infrastructure.datasource.mysql.impl.payment').projectDir = file('infrastructure/datasource/mysql/datasource-mysql-impl-payment')
include(':infrastructure.datasource.mysql.impl.product')
project(':infrastructure.datasource.mysql.impl.product').projectDir = file('infrastructure/datasource/mysql/datasource-mysql-impl-product')
include(':infrastructure.datasource.mysql.impl.user')
project(':infrastructure.datasource.mysql.impl.user').projectDir = file('infrastructure/datasource/mysql/datasource-mysql-impl-user')

// Datasource::Postgres
include(':infrastructure.datasource.postgres.core')
project(':infrastructure.datasource.postgres.core').projectDir = file('infrastructure/datasource/postgres/datasource-postgres-core')
include(':infrastructure.datasource.postgres.impl.auth')
project(':infrastructure.datasource.postgres.impl.auth').projectDir = file('infrastructure/datasource/postgres/datasource-postgres-impl-auth')
include(':infrastructure.datasource.postgres.impl.notification')
project(':infrastructure.datasource.postgres.impl.notification').projectDir = file('infrastructure/datasource/postgres/datasource-postgres-impl-notification')
include(':infrastructure.datasource.postgres.impl.order')
project(':infrastructure.datasource.postgres.impl.order').projectDir = file('infrastructure/datasource/postgres/datasource-postgres-impl-order')
include(':infrastructure.datasource.postgres.impl.payment')
project(':infrastructure.datasource.postgres.impl.payment').projectDir = file('infrastructure/datasource/postgres/datasource-postgres-impl-payment')
include(':infrastructure.datasource.postgres.impl.product')
project(':infrastructure.datasource.postgres.impl.product').projectDir = file('infrastructure/datasource/postgres/datasource-postgres-impl-product')
include(':infrastructure.datasource.postgres.impl.user')
project(':infrastructure.datasource.postgres.impl.user').projectDir = file('infrastructure/datasource/postgres/datasource-postgres-impl-user')

// Discovery client
include(':infrastructure.discovery-client.eureka')
project(':infrastructure.discovery-client.eureka').projectDir = file('infrastructure/discovery-client/discovery-client-eureka')
include(':infrastructure.discovery-client.kubernetes')
project(':infrastructure.discovery-client.kubernetes').projectDir = file('infrastructure/discovery-client/discovery-client-kubernetes')

// File

// File::CSV

// File::CSV::OpenCSV
include(':infrastructure.file.csv.opencsv.core')
project(':infrastructure.file.csv.opencsv.core').projectDir = file('infrastructure/file/csv/opencsv/csv-opencsv-core')
include(':infrastructure.file.csv.opencsv.impl.product')
project(':infrastructure.file.csv.opencsv.impl.product').projectDir = file('infrastructure/file/csv/opencsv/csv-opencsv-impl-product')

// File::Excel

// File::Excel::Easyexcel
include(':infrastructure.file.excel.easyexcel.core')
project(':infrastructure.file.excel.easyexcel.core').projectDir = file('infrastructure/file/excel/easyexcel/excel-easyexcel-core')
include(':infrastructure.file.excel.easyexcel.impl.product')
project(':infrastructure.file.excel.easyexcel.impl.product').projectDir = file('infrastructure/file/excel/easyexcel/excel-easyexcel-impl-product')

// File::Excel::Poi
include(':infrastructure.file.excel.poi.core')
project(':infrastructure.file.excel.poi.core').projectDir = file('infrastructure/file/excel/poi/excel-poi-core')
include(':infrastructure.file.excel.poi.impl.product')
project(':infrastructure.file.excel.poi.impl.product').projectDir = file('infrastructure/file/excel/poi/excel-poi-impl-product')

// File::PDF

// File::PDF::PDFBox
include(':infrastructure.file.pdf.pdfbox.core')
project(':infrastructure.file.pdf.pdfbox.core').projectDir = file('infrastructure/file/pdf/pdfbox/pdf-pdfbox-core')
include(':infrastructure.file.pdf.pdfbox.impl.product')
project(':infrastructure.file.pdf.pdfbox.impl.product').projectDir = file('infrastructure/file/pdf/pdfbox/pdf-pdfbox-impl-product')

// Internal API

// Internal API::Auth API
include(':infrastructure.internal-api.auth.rest.apachehttpclient')
project(':infrastructure.internal-api.auth.rest.apachehttpclient').projectDir = file('infrastructure/internal-api/auth-api/auth-api-rest-apachehttpclient')
include(':infrastructure.internal-api.auth.rest.feign')
project(':infrastructure.internal-api.auth.rest.feign').projectDir = file('infrastructure/internal-api/auth-api/auth-api-rest-feign')
include(':infrastructure.internal-api.auth.rest.restclient')
project(':infrastructure.internal-api.auth.rest.restclient').projectDir = file('infrastructure/internal-api/auth-api/auth-api-rest-restclient')
include(':infrastructure.internal-api.auth.rest.resttemplate')
project(':infrastructure.internal-api.auth.rest.resttemplate').projectDir = file('infrastructure/internal-api/auth-api/auth-api-rest-resttemplate')

// Internal API::Product API
include(':infrastructure.internal-api.product.grpc.netdevh')
project(':infrastructure.internal-api.product.grpc.netdevh').projectDir = file('infrastructure/internal-api/product-api/product-api-grpc-netdevh')
include(':infrastructure.internal-api.product.rest.apachehttpclient')
project(':infrastructure.internal-api.product.rest.apachehttpclient').projectDir = file('infrastructure/internal-api/product-api/product-api-rest-apachehttpclient')
include(':infrastructure.internal-api.product.rest.feign')
project(':infrastructure.internal-api.product.rest.feign').projectDir = file('infrastructure/internal-api/product-api/product-api-rest-feign')
include(':infrastructure.internal-api.product.rest.restclient')
project(':infrastructure.internal-api.product.rest.restclient').projectDir = file('infrastructure/internal-api/product-api/product-api-rest-restclient')
include(':infrastructure.internal-api.product.rest.resttemplate')
project(':infrastructure.internal-api.product.rest.resttemplate').projectDir = file('infrastructure/internal-api/product-api/product-api-rest-resttemplate')

// Internal API::User API
include(':infrastructure.internal-api.user.grpc.netdevh')
project(':infrastructure.internal-api.user.grpc.netdevh').projectDir = file('infrastructure/internal-api/user-api/user-api-grpc-netdevh')
include(':infrastructure.internal-api.user.rest.apachehttpclient')
project(':infrastructure.internal-api.user.rest.apachehttpclient').projectDir = file('infrastructure/internal-api/user-api/user-api-rest-apachehttpclient')
include(':infrastructure.internal-api.user.rest.feign')
project(':infrastructure.internal-api.user.rest.feign').projectDir = file('infrastructure/internal-api/user-api/user-api-rest-feign')
include(':infrastructure.internal-api.user.rest.restclient')
project(':infrastructure.internal-api.user.rest.restclient').projectDir = file('infrastructure/internal-api/user-api/user-api-rest-restclient')
include(':infrastructure.internal-api.user.rest.resttemplate')
project(':infrastructure.internal-api.user.rest.resttemplate').projectDir = file('infrastructure/internal-api/user-api/user-api-rest-resttemplate')

// Key-Value Store

// Key-Value Store::Redis
include(':infrastructure.kv-store.redis')
project(':infrastructure.kv-store.redis').projectDir = file('infrastructure/kv-store/redis/kv-store-redis')
include(':infrastructure.kv-store.redis-reactive')
project(':infrastructure.kv-store.redis-reactive').projectDir = file('infrastructure/kv-store/redis/kv-store-redis-reactive')
include(':infrastructure.kv-store.redis.connector.cluster')
project(':infrastructure.kv-store.redis.connector.cluster').projectDir = file('infrastructure/kv-store/redis/kv-store-redis-connector-cluster')
include(':infrastructure.kv-store.redis.connector.standalone')
project(':infrastructure.kv-store.redis.connector.standalone').projectDir = file('infrastructure/kv-store/redis/kv-store-redis-connector-standalone')

// Messaging

// Messaging::Kafka
include(':infrastructure.messaging.kafka.core')
project(':infrastructure.messaging.kafka.core').projectDir = file('infrastructure/messaging/kafka/messaging-kafka-core')
include(':infrastructure.messaging.kafka.impl.notification')
project(':infrastructure.messaging.kafka.impl.notification').projectDir = file('infrastructure/messaging/kafka/messaging-kafka-impl-notification')
include(':infrastructure.messaging.kafka.impl.order')
project(':infrastructure.messaging.kafka.impl.order').projectDir = file('infrastructure/messaging/kafka/messaging-kafka-impl-order')
include(':infrastructure.messaging.kafka.impl.payment')
project(':infrastructure.messaging.kafka.impl.payment').projectDir = file('infrastructure/messaging/kafka/messaging-kafka-impl-payment')
include(':infrastructure.messaging.kafka.impl.product')
project(':infrastructure.messaging.kafka.impl.product').projectDir = file('infrastructure/messaging/kafka/messaging-kafka-impl-product')
include(':infrastructure.messaging.kafka.impl.user')
project(':infrastructure.messaging.kafka.impl.user').projectDir = file('infrastructure/messaging/kafka/messaging-kafka-impl-user')

// Messaging::RabbitMQ
include(':infrastructure.messaging.rabbitmq.core')
project(':infrastructure.messaging.rabbitmq.core').projectDir = file('infrastructure/messaging/rabbitmq/messaging-rabbitmq-core')
include(':infrastructure.messaging.rabbitmq.impl.notification')
project(':infrastructure.messaging.rabbitmq.impl.notification').projectDir = file('infrastructure/messaging/rabbitmq/messaging-rabbitmq-impl-notification')
include(':infrastructure.messaging.rabbitmq.impl.order')
project(':infrastructure.messaging.rabbitmq.impl.order').projectDir = file('infrastructure/messaging/rabbitmq/messaging-rabbitmq-impl-order')
include(':infrastructure.messaging.rabbitmq.impl.payment')
project(':infrastructure.messaging.rabbitmq.impl.payment').projectDir = file('infrastructure/messaging/rabbitmq/messaging-rabbitmq-impl-payment')
include(':infrastructure.messaging.rabbitmq.impl.product')
project(':infrastructure.messaging.rabbitmq.impl.product').projectDir = file('infrastructure/messaging/rabbitmq/messaging-rabbitmq-impl-product')
include(':infrastructure.messaging.rabbitmq.impl.user')
project(':infrastructure.messaging.rabbitmq.impl.user').projectDir = file('infrastructure/messaging/rabbitmq/messaging-rabbitmq-impl-user')

// Migration

// Migration::Flyway

// Migration::Flyway::MySQL
include(':infrastructure.migration.flyway.mysql.core')
project(':infrastructure.migration.flyway.mysql.core').projectDir = file('infrastructure/migration/flyway/mysql/migration-flyway-mysql-core')
include(':infrastructure.migration.flyway.mysql.impl.auth')
project(':infrastructure.migration.flyway.mysql.impl.auth').projectDir = file('infrastructure/migration/flyway/mysql/migration-flyway-mysql-impl-auth')
include(':infrastructure.migration.flyway.mysql.impl.notification')
project(':infrastructure.migration.flyway.mysql.impl.notification').projectDir = file('infrastructure/migration/flyway/mysql/migration-flyway-mysql-impl-notification')
include(':infrastructure.migration.flyway.mysql.impl.order')
project(':infrastructure.migration.flyway.mysql.impl.order').projectDir = file('infrastructure/migration/flyway/mysql/migration-flyway-mysql-impl-order')
include(':infrastructure.migration.flyway.mysql.impl.outbox')
project(':infrastructure.migration.flyway.mysql.impl.outbox').projectDir = file('infrastructure/migration/flyway/mysql/migration-flyway-mysql-impl-outbox')
include(':infrastructure.migration.flyway.mysql.impl.payment')
project(':infrastructure.migration.flyway.mysql.impl.payment').projectDir = file('infrastructure/migration/flyway/mysql/migration-flyway-mysql-impl-payment')
include(':infrastructure.migration.flyway.mysql.impl.product')
project(':infrastructure.migration.flyway.mysql.impl.product').projectDir = file('infrastructure/migration/flyway/mysql/migration-flyway-mysql-impl-product')
include(':infrastructure.migration.flyway.mysql.impl.quartz')
project(':infrastructure.migration.flyway.mysql.impl.quartz').projectDir = file('infrastructure/migration/flyway/mysql/migration-flyway-mysql-impl-quartz')
include(':infrastructure.migration.flyway.mysql.impl.saga')
project(':infrastructure.migration.flyway.mysql.impl.saga').projectDir = file('infrastructure/migration/flyway/mysql/migration-flyway-mysql-impl-saga')
include(':infrastructure.migration.flyway.mysql.impl.user')
project(':infrastructure.migration.flyway.mysql.impl.user').projectDir = file('infrastructure/migration/flyway/mysql/migration-flyway-mysql-impl-user')

// Migration::Flyway::Postgres
include(':infrastructure.migration.flyway.postgres.core')
project(':infrastructure.migration.flyway.postgres.core').projectDir = file('infrastructure/migration/flyway/postgres/migration-flyway-postgres-core')
include(':infrastructure.migration.flyway.postgres.impl.auth')
project(':infrastructure.migration.flyway.postgres.impl.auth').projectDir = file('infrastructure/migration/flyway/postgres/migration-flyway-postgres-impl-auth')
include(':infrastructure.migration.flyway.postgres.impl.notification')
project(':infrastructure.migration.flyway.postgres.impl.notification').projectDir = file('infrastructure/migration/flyway/postgres/migration-flyway-postgres-impl-notification')
include(':infrastructure.migration.flyway.postgres.impl.order')
project(':infrastructure.migration.flyway.postgres.impl.order').projectDir = file('infrastructure/migration/flyway/postgres/migration-flyway-postgres-impl-order')
include(':infrastructure.migration.flyway.postgres.impl.outbox')
project(':infrastructure.migration.flyway.postgres.impl.outbox').projectDir = file('infrastructure/migration/flyway/postgres/migration-flyway-postgres-impl-outbox')
include(':infrastructure.migration.flyway.postgres.impl.payment')
project(':infrastructure.migration.flyway.postgres.impl.payment').projectDir = file('infrastructure/migration/flyway/postgres/migration-flyway-postgres-impl-payment')
include(':infrastructure.migration.flyway.postgres.impl.product')
project(':infrastructure.migration.flyway.postgres.impl.product').projectDir = file('infrastructure/migration/flyway/postgres/migration-flyway-postgres-impl-product')
include(':infrastructure.migration.flyway.postgres.impl.quartz')
project(':infrastructure.migration.flyway.postgres.impl.quartz').projectDir = file('infrastructure/migration/flyway/postgres/migration-flyway-postgres-impl-quartz')
include(':infrastructure.migration.flyway.postgres.impl.saga')
project(':infrastructure.migration.flyway.postgres.impl.saga').projectDir = file('infrastructure/migration/flyway/postgres/migration-flyway-postgres-impl-saga')
include(':infrastructure.migration.flyway.postgres.impl.user')
project(':infrastructure.migration.flyway.postgres.impl.user').projectDir = file('infrastructure/migration/flyway/postgres/migration-flyway-postgres-impl-user')

// Notification

// Notification::Email

// Notification::Email::Spring
include(':infrastructure.notification.email.spring')
project(':infrastructure.notification.email.spring').projectDir = file('infrastructure/notification/email/email-spring')

// Notification::Email::Sendgrid
include(':infrastructure.notification.email.sendgrid')
project(':infrastructure.notification.email.sendgrid').projectDir = file('infrastructure/notification/email/email-sendgrid')

// Notification::In-App

// Realtime::In-App::SSE
include(':infrastructure.notification.inapp.sse')
project(':infrastructure.notification.inapp.sse').projectDir = file('infrastructure/notification/inapp/inapp-sse')

// Realtime::In-App::WebSocket
include(':infrastructure.notification.inapp.websocket')
project(':infrastructure.notification.inapp.websocket').projectDir = file('infrastructure/notification/inapp/inapp-websocket')

// Observability

// Observability::Actuator
include(':infrastructure.observability.actuator')
project(':infrastructure.observability.actuator').projectDir = file('infrastructure/observability/actuator')

// Observability::Logging
include(':infrastructure.observability.logging.logback')
project(':infrastructure.observability.logging.logback').projectDir = file('infrastructure/observability/logging/logging-logback')

// Observability::Metrics
include(':infrastructure.observability.metrics.prometheus')
project(':infrastructure.observability.metrics.prometheus').projectDir = file('infrastructure/observability/metrics/metrics-prometheus')

// Observability::Tracing
include(':infrastructure.observability.tracing.zipkin')
project(':infrastructure.observability.tracing.zipkin').projectDir = file('infrastructure/observability/tracing/tracing-zipkin')

// Payment
include(':infrastructure.payment.parent')
project(':infrastructure.payment.parent').projectDir = file('infrastructure/payment/payment-parent')

// Payment::Simulator
include(':infrastructure.payment.simulator')
project(':infrastructure.payment.simulator').projectDir = file('infrastructure/payment/payment-simulator')

// Payment::Stripe
include(':infrastructure.payment.stripe')
project(':infrastructure.payment.stripe').projectDir = file('infrastructure/payment/payment-stripe')

// Persistence

// Persistence::JPA
include(':infrastructure.persistence.jpa.core')
project(':infrastructure.persistence.jpa.core').projectDir = file('infrastructure/persistence/jpa/persistence-jpa-core')
include(':infrastructure.persistence.jpa.impl.auth')
project(':infrastructure.persistence.jpa.impl.auth').projectDir = file('infrastructure/persistence/jpa/persistence-jpa-impl-auth')
include(':infrastructure.persistence.jpa.impl.notification')
project(':infrastructure.persistence.jpa.impl.notification').projectDir = file('infrastructure/persistence/jpa/persistence-jpa-impl-notification')
include(':infrastructure.persistence.jpa.impl.order')
project(':infrastructure.persistence.jpa.impl.order').projectDir = file('infrastructure/persistence/jpa/persistence-jpa-impl-order')
include(':infrastructure.persistence.jpa.impl.outbox')
project(':infrastructure.persistence.jpa.impl.outbox').projectDir = file('infrastructure/persistence/jpa/persistence-jpa-impl-outbox')
include(':infrastructure.persistence.jpa.impl.payment')
project(':infrastructure.persistence.jpa.impl.payment').projectDir = file('infrastructure/persistence/jpa/persistence-jpa-impl-payment')
include(':infrastructure.persistence.jpa.impl.product')
project(':infrastructure.persistence.jpa.impl.product').projectDir = file('infrastructure/persistence/jpa/persistence-jpa-impl-product')
include(':infrastructure.persistence.jpa.impl.saga')
project(':infrastructure.persistence.jpa.impl.saga').projectDir = file('infrastructure/persistence/jpa/persistence-jpa-impl-saga')
include(':infrastructure.persistence.jpa.impl.user')
project(':infrastructure.persistence.jpa.impl.user').projectDir = file('infrastructure/persistence/jpa/persistence-jpa-impl-user')

// Resilience
include(':infrastructure.resilience.resilience4j')
project(':infrastructure.resilience.resilience4j').projectDir = file('infrastructure/resilience/resilience-resilience4j')

// Scheduler

// Scheduler::Spring
include(':infrastructure.scheduler.spring.core')
project(':infrastructure.scheduler.spring.core').projectDir = file('infrastructure/scheduler/spring/scheduler-spring-core')
include(':infrastructure.scheduler.spring.impl.outbox')
project(':infrastructure.scheduler.spring.impl.outbox').projectDir = file('infrastructure/scheduler/spring/scheduler-spring-impl-outbox')

// Scheduler::Quartz
include(':infrastructure.scheduler.quartz.core')
project(':infrastructure.scheduler.quartz.core').projectDir = file('infrastructure/scheduler/quartz/scheduler-quartz-core')
include(':infrastructure.scheduler.quartz.jobstore.mysql')
project(':infrastructure.scheduler.quartz.jobstore.mysql').projectDir = file('infrastructure/scheduler/quartz/scheduler-quartz-jobstore-mysql')
include(':infrastructure.scheduler.quartz.jobstore.postgres')
project(':infrastructure.scheduler.quartz.jobstore.postgres').projectDir = file('infrastructure/scheduler/quartz/scheduler-quartz-jobstore-postgres')
include(':infrastructure.scheduler.quartz.impl.outbox')
project(':infrastructure.scheduler.quartz.impl.outbox').projectDir = file('infrastructure/scheduler/quartz/scheduler-quartz-impl-outbox')

// Search

// Search::Elasticsearch
include(':infrastructure.search.elasticsearch.core')
project(':infrastructure.search.elasticsearch.core').projectDir = file('infrastructure/search/elasticsearch/search-elasticsearch-core')
include(':infrastructure.search.elasticsearch.impl.product')
project(':infrastructure.search.elasticsearch.impl.product').projectDir = file('infrastructure/search/elasticsearch/search-elasticsearch-impl-product')

// Sequence generator
include(':infrastructure.sequence-generator')
project(':infrastructure.sequence-generator').projectDir = file('infrastructure/sequence-generator')

// Storage
include(':infrastructure.storage.filesystem')
project(':infrastructure.storage.filesystem').projectDir = file('infrastructure/storage/storage-filesystem')
include(':infrastructure.storage.minio')
project(':infrastructure.storage.minio').projectDir = file('infrastructure/storage/storage-minio')

// Template
include(':infrastructure.template.freemarker')
project(':infrastructure.template.freemarker').projectDir = file('infrastructure/template/template-freemarker')
include(':infrastructure.template.thymeleaf')
project(':infrastructure.template.thymeleaf').projectDir = file('infrastructure/template/template-thymeleaf')

// =================================================================================================
// Application
// =================================================================================================

include(':application.notification')
project(':application.notification').projectDir = file('application/notification-application')

include(':application.order')
project(':application.order').projectDir = file('application/order-application')

include(':application.payment')
project(':application.payment').projectDir = file('application/payment-application')

include(':application.product')
project(':application.product').projectDir = file('application/product-application')

include(':application.user')
project(':application.user').projectDir = file('application/user-application')

// =================================================================================================
// Edge
// =================================================================================================

// API Gateway

// API Gateway::Spring Cloud Gateway
include(':edge.api-gateway.spring-cloud-gateway.server')
project(':edge.api-gateway.spring-cloud-gateway.server').projectDir = file('edge/api-gateway/spring-cloud-gateway/spring-cloud-gateway-server')
include(':edge.api-gateway.spring-cloud-gateway.security.core')
project(':edge.api-gateway.spring-cloud-gateway.security.core').projectDir = file('edge/api-gateway/spring-cloud-gateway/spring-cloud-gateway-security-core')
include(':edge.api-gateway.spring-cloud-gateway.security.spring-security-jwt')
project(':edge.api-gateway.spring-cloud-gateway.security.spring-security-jwt').projectDir = file('edge/api-gateway/spring-cloud-gateway/spring-cloud-gateway-security-spring-security-jwt')
include(':edge.api-gateway.spring-cloud-gateway.security.keycloak')
project(':edge.api-gateway.spring-cloud-gateway.security.keycloak').projectDir = file('edge/api-gateway/spring-cloud-gateway/spring-cloud-gateway-security-keycloak')

// Auth Server
include(':edge.auth-server.keycloak')
project(':edge.auth-server.keycloak').projectDir = file('edge/auth-server/auth-server-keycloak')
include(':edge.auth-server.spring-security-jwt')
project(':edge.auth-server.spring-security-jwt').projectDir = file('edge/auth-server/auth-server-spring-security-jwt')

// Config Server
include(':edge.config-server.spring-cloud-config')
project(':edge.config-server.spring-cloud-config').projectDir = file('edge/config-server/config-server-spring-cloud-config')

// Discovery Server
include(':edge.discovery-server.eureka')
project(':edge.discovery-server.eureka').projectDir = file('edge/discovery-server/discovery-server-eureka')
