syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.atlas.libs.protobuf.identity";

import "google/protobuf/empty.proto";

package identity;

service UserService {
  rpc ListUser (ListUserRequestProto) returns (ListUserResponseProto) {};
}

message ListUserRequestProto {
  repeated string id = 1;
}

message UserProto {
  string id = 1;
  string first_name = 2;
  string last_name = 3;
  string email = 4;
  string phone_number = 5;
  string role = 6;
}

message ListUserResponseProto {
  repeated UserProto user = 1;
}
