plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Domain
    api project(':domain.notification')

    // Infrastructure
    api project(':infrastructure.spring-boot.bootstrap')
    switch (infraStack['config']) {
        case 'yaml':
            api project(':infrastructure.spring-boot.config.yaml')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${infraStack['config']}")
    }
    switch (infraStack['datasource']) {
        case 'mysql':
            api project(':infrastructure.spring-boot.datasource.mysql.adapter.notification')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${infraStack['datasource']}")
    }
    switch (infraStack['discovery-client']) {
        case 'none':
            break
        case 'eureka':
            api project(':infrastructure.spring-boot.discovery-client.eureka')
            break
        case 'kubernetes':
            api project(':infrastructure.spring-boot.discovery-client.kubernetes')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${infraStack['discovery-client']}")
    }
    switch (infraStack['messaging']) {
        case 'kafka':
            api project(':infrastructure.spring-boot.messaging.kafka.adapter.notification')
            break
        case 'sns':
            api project(':infrastructure.spring-boot.messaging.sns.adapter.notification')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${infraStack['messaging']}")
    }
    api project(':infrastructure.spring-boot.event.event-handler-decorator')
    switch (infraStack['notification.email']) {
        case 'spring':
            api project(':infrastructure.spring-boot.notification.email.spring')
            break
        case 'ses':
            api project(':infrastructure.spring-boot.notification.email.ses')
            break
        case 'sendgrid':
            api project(':infrastructure.spring-boot.notification.email.sendgrid')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${infraStack['email']}")
    }
    api project(':infrastructure.spring-boot.observability.actuator')
    switch (infraStack['observability.logging']) {
        case 'logback':
            api project(':infrastructure.spring-boot.observability.logging.logback')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${infraStack['observability.logging']}")
    }
    switch (infraStack['observability.metrics']) {
        case 'none':
            break;
        case 'prometheus':
            api project(':infrastructure.spring-boot.observability.metrics.prometheus')
            break
        case 'cloudwatch':
            api project(':infrastructure.spring-boot.observability.metrics.cloudwatch')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${infraStack['observability.metrics']}")
    }
    switch (infraStack['observability.tracing']) {
        case 'simple':
            api project(':infrastructure.spring-boot.observability.tracing.simple')
            break
        case 'zipkin':
            api project(':infrastructure.spring-boot.observability.tracing.zipkin')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${infraStack['observability.tracing']}")
    }
    switch (infraStack['scheduler']) {
        case 'spring':
            api project(':infrastructure.spring-boot.scheduler.spring.adapter.notification')
            break
        case 'quartz':
            api project(':infrastructure.spring-boot.scheduler.quartz.adapter.notification')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${infraStack['scheduler']}")
    }
    api project(':infrastructure.spring-boot.notification.sse')
    switch (infraStack['template']) {
        case 'freemarker':
            api project(':infrastructure.spring-boot.template.freemarker')
            break
        case 'thymeleaf':
            api project(':infrastructure.spring-boot.template.thymeleaf')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${infraStack['template']}")
    }
    api project(':infrastructure.spring-boot.use-case.use-case-handler-decorator')
    api project(':infrastructure.spring-boot.notification.websocket')
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

test {
    useJUnitPlatform()
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
