{{- if eq .Values.appStack.storage "minio" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ lower $.Release.Name }}-minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  root-user: {{ .Values.minio.secrets.rootUser }}
  root-password: {{ .Values.minio.secrets.rootPassword }}
{{- end }}
