apiVersion: v1
kind: Service
metadata:
  name: {{ lower $.Release.Name }}-catalog-service
  labels:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    app.kubernetes.io/name: catalog-service
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
  type: {{ .Values.global.service.type }}
  ports:
    - name: http
      port: {{ .Values.global.catalogSvc.service.ports.http }}
      targetPort: http
    {{- if eq .Values.global.appStack.internal "grpc" }}
    - name: grpc
      port: {{ .Values.global.catalogSvc.service.ports.grpc }}
      targetPort: grpc
    {{- end }}
