plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Lib
    implementation 'org.springframework.boot:spring-boot-starter-security'

    implementation project(':framework')
    implementation project(':auth-server.domain')
    implementation project(':api-server.rest')
    switch (rootProject.ext.appStack['datasource']) {
        case 'mysql':
            implementation project(':auth-server.datasource.mysql')
            break
        case 'postgres':
            implementation project(':auth-server.datasource.postgres')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['datasource']}")
    }
    switch (rootProject.ext.appStack['discovery-client']) {
        case 'none':
            break
        case 'eureka':
            implementation project(':discovery-client.eureka')
            break
        case 'kubernetes':
            implementation project(':discovery-client.kubernetes')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['discovery-client']}")
    }
    switch (rootProject.ext.appStack['kv-store']) {
        case 'redis':
            implementation project(':kv-store.redis')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['kv-store']}")
    }
    switch (rootProject.ext.appStack['migration']) {
        case 'flyway':
            switch (rootProject.ext.appStack['datasource']) {
                case 'mysql':
                    implementation project(':auth-server.migration.flyway.mysql')
                    break
                case 'postgres':
                    implementation project(':auth-server.migration.flyway.postgres')
                    break
                default:
                    throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['datasource']}")
            }
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['migration']}")
    }
    implementation project(':observability')
    switch (rootProject.ext.appStack['persistence']) {
        case 'jpa':
            implementation project(':auth-server.persistence.jpa')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['persistence']}")
    }

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Mapstruct
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
