apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-gateway-logs
  labels:
    app: api-gateway
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 
