{{- if eq .Values.global.appStack.idp "spring" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ lower $.Release.Name }}-authorization-server
  labels:
    app.kubernetes.io/name: authorization-server
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.global.service.type }}
  selector:
    app.kubernetes.io/name: authorization-server
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
  ports:
    - name: http
      port: {{ .Values.global.authorizationServer.service.ports.http }}
      targetPort: http
{{- end }}
