datasource: mysql
file:
  csv: opencsv
  excel: poi
  pdf: pdfbox
idp: keycloak
internal: rest
kv-store: redis
messaging: kafka
migration: flyway
notification:
  email: spring
observability:
  logging:
    stack: none
    framework: logback
  metrics: none
  tracing: none
persistence: jpa
redis: standalone
scheduler: quartz
search: elasticsearch
service-discovery: eureka
storage: minio
template: thymeleaf
