datasource: mysql
file:
  csv: opencsv
  excel: poi
  pdf: pdfbox
idp: spring
internal: rest
kv-store: redis
messaging: kafka
migration: flyway
notification:
  email: spring
observability:
  logging:
    stack: loki
    framework: logback
  metrics: prometheus
  tracing: zipkin
persistence: jpa
redis: standalone
scheduler: quartz
search: elasticsearch
service-discovery: kubernetes
storage: minio
template: freemarker
