deployment: local-compose
datasource: mysql
file:
  csv: opencsv
  excel: poi
  pdf: pdfbox
full-text-search: elasticsearch
identity: keycloak
internal: rest
kv-store: redis
messaging: kafka
migration: flyway
notification:
  email: spring
persistence: jpa
redis: standalone
scheduler: quartz
service-discovery: eureka
storage: minio
template: freemarker
