plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Lombok
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    // Spring
    api 'org.springframework.boot:spring-boot-starter-aop'
    api 'org.springframework.boot:spring-boot-starter-json'
    api 'org.springframework.boot:spring-boot-starter-validation'
    api "org.springframework:spring-tx:${springFrameworkVersion}"

    // Commons
    api 'org.apache.commons:commons-lang3:3.18.0'
    api 'org.apache.commons:commons-collections4:4.4'
    api 'commons-io:commons-io:2.18.0'
    api 'commons-codec:commons-codec:1.18.0'
    api 'com.google.guava:guava:33.3.1-jre'

    // Reactor
    api "io.projectreactor:reactor-core:${ioProjectReactorVersion}"

    // QR generator
    api 'com.google.zxing:core:3.5.3'
    api 'com.google.zxing:javase:3.5.3'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
