plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    api project(':libs.framework')

    api 'org.springframework.boot:spring-boot-starter-data-redis'

    switch (rootProject.ext.appStack['redis']) {
        case 'standalone':
            api project(':libs.kv-store.redis.connector.standalone')
            break
        case 'cluster':
            api project(':libs.kv-store.redis.connector.cluster')
            break
        default:
            throw new IllegalArgumentException("Unsupported redis: ${rootProject.ext.appStack['redis']}")
    }

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}


idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
