apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notification-service-logs
  labels:
    app: notification-service

    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 
