plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Domain
    implementation project(':auth-server.domain')

    // Shared
    implementation project(':framework')
    implementation project(':api-server.rest')
    switch (rootProject.ext.appStack['discovery-client']) {
        case 'none':
            break
        case 'eureka':
            implementation project(':discovery-client.eureka')
            break
        case 'kubernetes':
            implementation project(':discovery-client.kubernetes')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['discovery-client']}")
    }
    implementation project(':iam.keycloak')
    implementation project(':observability')

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Mapstruct
    implementation "org.mapstruct:mapstruct:${mapstructVersion}"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
