{{- if .Values.global.apiGateway.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: {{ .Values.global.apiGateway.ingress.alb.scheme }}
    {{- if .Values.global.apiGateway.ingress.alb.groupName }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.global.apiGateway.ingress.alb.groupName | quote }}
    {{- end }}
    {{- if .Values.global.apiGateway.ingress.alb.certificateArn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.global.apiGateway.ingress.alb.certificateArn | quote }}
    {{- else }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    {{- end }}
    {{- with .Values.global.apiGateway.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: alb
  rules:
    - {{- if and .Values.global.apiGateway.ingress.host (ne .Values.global.apiGateway.ingress.host "") }}
      host: {{ .Values.global.apiGateway.ingress.host | quote }}
      {{- end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: {{ .Values.global.apiGateway.service.ports.http }}
{{- end }}
