{{- if eq .Values.global.appStack.ai.vectorstore.qdrant true }}
apiVersion: v1
kind: Service
metadata:
  name: qdrant
  labels:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
  ports:
    - name: http
      port: {{ .Values.global.qdrant.service.ports.http }}
      targetPort: http
    - name: grpc
      port: {{ .Values.global.qdrant.service.ports.grpc }}
      targetPort: grpc
{{- end }}
