apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  selector:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.global.service.type }}
  ports:
    - name: http
      port: {{ .Values.inventorySvc.service.ports.http }}
      targetPort: http
