spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  messaging:
    rabbitmq:
      exchanges:
        - name: user_events
          type: TOPIC
        - name: product_events
          type: TOPIC
        - name: order_events
          type: TOPIC
      queues:
        # Product Service queues
        - name: product_svc.order_events
        # Order Service queues
        - name: order_svc.product_events
        # Notification Service queues
        - name: notification_svc.order_events
      bindings:
        # Product Service bindings
        - exchange: order_events
          queue: product_svc.order_events
          routing-key: order_created
        # Order Service bindings
        - exchange: product_events
          queue: order_svc.product_events
          routing-key: reserve_quantity_*
        # Notification Service bindings
        - exchange: order_events
          queue: notification_svc.order_events
          routing-key: order_confirmed
        - exchange: order_events
          queue: notification_svc.order_events
          routing-key: order_canceled
