plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    switch (rootProject.ext.appStack['observability.logging.framework']) {
        case 'logback':
            api project(':libs.observability.logging.logback')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.logging.framework: ${rootProject.ext.appStack['observability.logging.framework']}")
    }
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}


idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
