{{- if eq .Values.global.appStack.datasource "mysql" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  root-password: {{ .Values.global.mysql.secrets.rootPassword }}
  user: {{ .Values.global.mysql.secrets.user }}
  password: {{ .Values.global.mysql.secrets.password }}
{{- end }}
{{- if eq .Values.global.appStack.datasource "postgres" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  user: {{ .Values.global.postgres.secrets.user }}
  password: {{ .Values.global.postgres.secrets.password }}
{{- end }}
{{- if eq .Values.global.appStack.messaging "rabbitmq" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  user: {{ .Values.global.rabbitmq.secrets.user }}
  password: {{ .Values.global.rabbitmq.secrets.password }}
{{- end }}
{{- if eq .Values.global.appStack.search "elasticsearch" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch
  labels:
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  password: {{ .Values.global.elasticsearch.secrets.password | quote }}
{{- end }}
{{- if eq .Values.global.appStack.storage "minio" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  root-user: {{ .Values.global.minio.secrets.rootUser }}
  root-password: {{ .Values.global.minio.secrets.rootPassword }}
{{- end }}
