{{- if eq .Values.global.appStack.idp "keycloak" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ lower $.Release.Name }}-keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  admin-username: {{ .Values.keycloak.secret.adminUsername }}
  admin-password: {{ .Values.keycloak.secret.adminPassword }}
{{- end }}
