syntax = "proto3";

option java_multiple_files = true;
option java_package = "org.atlas.infrastructure.api.server.grpc.protobuf.payment";

import "google/protobuf/empty.proto";

package payment;

service PaymentService {
  rpc ListPayment (ListPaymentRequestProto) returns (ListPaymentResponseProto) {};
}

message ListPaymentRequestProto {
  repeated int32 order_id = 1;
}

message PaymentProto {
  int32 id = 1;
  double amount = 2;
  string currency = 3;
  string method = 4;
  string gateway = 5;
  string status = 6;
  string error_code = 7;
  string error_message = 8;
  string cancellation_reason = 9;
}

message ListPaymentResponseProto {
  repeated PaymentProto payment = 1;
}
