{{- if eq .Values.appStack.datasource "mysql" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ lower $.Release.Name }}-mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  initdb.sh: |
{{ tpl (.Files.Get "files/mysql/initdb.sh.tpl") . | indent 4 }}
{{- end }}
