spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_payment}
    username: ${DB_USERNAME:atlas}
    password: ${DB_PASSWORD:secret123456}
