spring:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
            instanceName: DefaultScheduler
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
            tablePrefix: QRTZ_
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
  datasource:
    quartz:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: ${QUARTZ_DB_URL:jdbc:mysql://localhost:3306/db_quartz?useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false}
      username: ${QUARTZ_DB_USERNAME:root}
      password: ${QUARTZ_DB_PASSWORD:root}
