apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kafka
  labels:
    app: kafka
    tier: infrastructure

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app: kafka
  tier: infrastructure 
