apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
    tier: infrastructure
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka-external
    - port: 29092
      targetPort: 29092
      name: kafka-internal
    - port: 9101
      targetPort: 9101
      name: jmx
  type: ClusterIP 
