plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Datasource
    switch (rootProject.ext.appStack['datasource']) {
        case 'mysql':
            api project(':services.order.datasource.mysql')
            break
        case 'postgres':
            api project(':services.order.datasource.postgres')
            break
        default:
            throw new IllegalArgumentException("Unsupported datasource: ${rootProject.ext.appStack['datasource']}")
    }

    // Internal
    switch (rootProject.ext.appStack['internal']) {
        case 'grpc':
            api project(':libs.internal.identity.grpc')
            api project(':libs.internal.catalog.grpc')
            break
        case 'rest':
            api project(':libs.internal.identity.rest')
            api project(':libs.internal.catalog.rest')
            break
        default:
            throw new IllegalArgumentException("Unsupported internal: ${rootProject.ext.appStack['internal']}")
    }

    // KV store
    switch (rootProject.ext.appStack['kv-store']) {
        case 'redis':
            api project(':libs.kv-store.redis')
            break
        default:
            throw new IllegalArgumentException("Unsupported kv-store: ${rootProject.ext.appStack['kv-store']}")
    }

    // Messaging
    switch (rootProject.ext.appStack['messaging']) {
        case 'kafka':
            api project(':services.order.messaging.kafka')
            break
        case 'rabbitmq':
            api project(':services.order.messaging.rabbitmq')
            break
        default:
            throw new IllegalArgumentException("Unsupported messaging: ${rootProject.ext.appStack['messaging']}")
    }

    // Migration
    switch (rootProject.ext.appStack['migration']) {
        case 'flyway':
            switch (rootProject.ext.appStack['datasource']) {
                case 'mysql':
                    api project(':services.order.migration.flyway.mysql')
                    break
                case 'postgres':
                    api project(':services.order.migration.flyway.postgres')
                    break
                default:
                    throw new IllegalArgumentException("Unsupported datasource: ${rootProject.ext.appStack['datasource']}")
            }
            break
        default:
            throw new IllegalArgumentException("Unsupported migration: ${rootProject.ext.appStack['migration']}")
    }

    // Notification::Email
    switch (rootProject.ext.appStack['notification.email']) {
        case 'spring':
            api project(':libs.notification.email.spring')
            break
        case 'sendgrid':
            api project(':libs.notification.email.sendgrid')
            break
        default:
            throw new IllegalArgumentException("Unsupported notification.email: ${rootProject.ext.appStack['notification.email']}")
    }

    // Observability
    api project(':libs.observability.actuator')
    switch (rootProject.ext.appStack['observability.logging.framework']) {
        case 'logback':
            api project(':libs.observability.logging.logback')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.logging.framework: ${rootProject.ext.appStack['observability.logging.framework']}")
    }
    switch (rootProject.ext.appStack['observability.metrics']) {
        case 'none':
            break;
        case 'prometheus':
            api project(':libs.observability.metrics.prometheus')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.metrics: ${rootProject.ext.appStack['observability.metrics']}")
    }
    switch (rootProject.ext.appStack['observability.tracing']) {
        case 'none':
            break
        case 'zipkin':
            api project(':libs.observability.tracing.zipkin')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.tracing: ${rootProject.ext.appStack['observability.tracing']}")
    }

    // Outbox
    api project(':libs.outbox')
    
    // Scheduler
    switch (rootProject.ext.appStack['scheduler']) {
        case 'spring':
            api project(':services.order.scheduler.spring')
            break
        case 'quartz':
            api project(':services.order.scheduler.quartz')
            break
        default:
            throw new IllegalArgumentException("Unsupported scheduler: ${rootProject.ext.appStack['scheduler']}")
    }

    // Persistence
    switch (rootProject.ext.appStack.persistence) {
        case 'jpa':
            api project(':services.order.persistence.jpa')
            break
        default:
            throw new IllegalArgumentException("Unsupported persistence: ${rootProject.ext.appStack.persistence}")
    }

    // Saga
    api project(':libs.saga')

    // Service discovery
    switch (rootProject.ext.appStack['service-discovery']) {
        case 'none':
            break
        case 'eureka':
            api project(':libs.discovery-client.eureka')
            break
        case 'kubernetes':
            api project(':libs.discovery-client.kubernetes')
            break
        default:
            throw new IllegalArgumentException("Unsupported service-discovery: ${rootProject.ext.appStack['service-discovery']}")
    }

    // Sequence generator
    api project(':libs.sequence-generator')

    // Template
    switch (rootProject.ext.appStack['template']) {
        case 'freemarker':
            api project(':libs.template.freemarker')
            break
        case 'thymeleaf':
            api project(':libs.template.thymeleaf')
            break
        default:
            throw new IllegalArgumentException("Unsupported template: ${rootProject.ext.appStack['template']}")
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.grpc:spring-grpc-dependencies:${springGrpcVersion}"
    }
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
