spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  messaging:
    rabbitmq:
      exchanges:
        - name: saga.checkout
          type: TOPIC
      queues:
        # Order service
        - name: order_svc.saga.checkout.command
        - name: order_svc.saga.checkout.compensation
        - name: order_svc.saga.checkout.command.reply
        - name: order_svc.saga.checkout.compensation.reply
        # Product service
        - name: product_svc.saga.checkout.command
        - name: product_svc.saga.checkout.compensation
        # Payment service
        - name: payment_svc.saga.checkout.command
        - name: payment_svc.saga.checkout.compensation
      bindings:
        # Order service
        - exchange: saga.checkout
          queue: order_svc.saga.checkout.command
          routing-key: saga.checkout.command
        - exchange: saga.checkout
          queue: order_svc.saga.checkout.compensation
          routing-key: saga.checkout.compensation
        - exchange: saga.checkout
          queue: order_svc.saga.checkout.command.reply
          routing-key: saga.checkout.command.reply
        - exchange: saga.checkout
          queue: order_svc.saga.checkout.compensation.reply
          routing-key: saga.checkout.compensation.reply
        # Product service
        - exchange: saga.checkout
          queue: product_svc.saga.checkout.command
          routing-key: saga.checkout.command
        - exchange: saga.checkout
          queue: product_svc.saga.checkout.compensation
          routing-key: saga.checkout.compensation
        # Payment service
        - exchange: saga.checkout
          queue: payment_svc.saga.checkout.command
          routing-key: saga.checkout.command
        - exchange: saga.checkout
          queue: payment_svc.saga.checkout.compensation
          routing-key: saga.checkout.compensation
