{{- if eq .Values.appStack.messaging "rabbitmq" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ lower $.Release.Name }}-rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  user: {{ .Values.rabbitmq.secrets.user }}
  password: {{ .Values.rabbitmq.secrets.password }}
{{- end }}
