{{- if eq .Values.appStack.messaging "rabbitmq" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ lower $.Release.Name }}-rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
  ports:
    - name: amqp
      port: {{ .Values.rabbitmq.service.ports.amqp }}
      targetPort: amqp
    - name: management
      port: {{ .Values.rabbitmq.service.ports.management }}
      targetPort: management
{{- end }}
