# =============================================================================
# Promtail Log Collection Agent Service
# =============================================================================

services:
  promtail:
    container_name: promtail
    image: grafana/promtail:main
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./config.yml:/etc/promtail/config.yml
      - user-service-log:/var/log/user-service
      - product-service-log:/var/log/product-service
      - order-service-log:/var/log/order-service
      - notification-service-log:/var/log/notification-service
      - eureka-server-log:/var/log/eureka-server
      - api-gateway-log:/var/log/api-gateway
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:9080/metrics || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - atlas-network

volumes:
  user-service-log:
  product-service-log:
  order-service-log:
  notification-service-log:
  eureka-server-log:
  api-gateway-log:

# Network is defined globally in main docker-compose.yml
