{{- if eq .Values.appStack.observability.tracing "zipkin" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ lower $.Release.Name }}-zipkin
  labels:
    app.kubernetes.io/name: zipkin
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  serviceName: zipkin
  replicas: {{ .Values.global.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: zipkin
      app.kubernetes.io/instance: {{ lower $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zipkin
        app.kubernetes.io/instance: {{ lower $.Release.Name }}
    spec:
      {{- include "atlas.nodeSelector.infrastructure" . | nindent 6 }}
      containers:
        - name: zipkin
          image: "{{ .Values.zipkin.image.repository }}:{{ .Values.zipkin.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: STORAGE_TYPE
              value: "mem"
          ports:
            - name: http
              containerPort: 9411
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{ toYaml .Values.zipkin.resources | nindent 12 }}
{{- end }}
