{{- if eq .Values.global.appStack.datasource "mysql" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ lower $.Release.Name }}-mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: {{ lower $.Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  root-password: {{ .Values.global.mysql.secrets.rootPassword }}
  user: {{ .Values.global.mysql.secrets.user }}
  password: {{ .Values.global.mysql.secrets.password }}
{{- end }}
