spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  messaging:
    rabbitmq:
      exchanges:
        - name: user_event
          type: TOPIC
        - name: product_event
          type: TOPIC
        - name: order_event
          type: TOPIC
      queues:
        # Product service
        - name: product_svc.order_event
        # Order service
        - name: order_svc.order_event
        # Notification service
        - name: notification_svc.order_event
      bindings:
        # Product service
        - exchange: order_event
          queue: product_svc.order_event
          routing-key: ORDER_CREATED
        # Order service
        - exchange: order_event
          queue: order_svc.order_event
          routing-key: RESERVE_QUANTITY_*
        # Notification service
        - exchange: order_event
          queue: notification_svc.order_event
          routing-key: ORDER_CONFIRMED
        - exchange: order_event
          queue: notification_svc.order_event
          routing-key: ORDER_CANCELED
