plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Framework
    implementation project(':libs.framework')

    // Spring Cloud Config Server
    implementation 'org.springframework.cloud:spring-cloud-config-server'

    // Observability
    switch (rootProject.ext.appStack['observability.logging.framework']) {
        case 'logback':
            implementation project(':libs.observability.logging.logback')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.logging.framework: ${rootProject.ext.appStack['observability.logging.framework']}")
    }
    switch (rootProject.ext.appStack['observability.metrics']) {
        case 'none':
            break;
        case 'prometheus':
            implementation project(':libs.observability.metrics.prometheus')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.metrics: ${rootProject.ext.appStack['observability.metrics']}")
    }
    switch (rootProject.ext.appStack['observability.tracing']) {
        case 'none':
            break
        case 'zipkin':
            implementation project(':libs.observability.tracing.zipkin')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.tracing: ${rootProject.ext.appStack['observability.tracing']}")
    }
    
    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}


idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
