plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Datasource
    switch (rootProject.ext.appStack['datasource']) {
        case 'mysql':
            api project(':services.catalog.datasource.mysql')
            break
        case 'postgres':
            api project(':services.catalog.datasource.postgres')
            break
        default:
            throw new IllegalArgumentException("Unsupported datasource: ${rootProject.ext.appStack['datasource']}")
    }
    
    // File::CSV
    switch (rootProject.ext.appStack['file.csv']) {
        case 'opencsv':
            api project(':services.catalog.file.csv.opencsv')
            break
        default:
            throw new IllegalArgumentException("Unsupported file.csv: ${rootProject.ext.appStack['file.csv']}")
    }
    
    // File::Excel
    switch (rootProject.ext.appStack['file.excel']) {
        case 'easyexcel':
            api project(':services.catalog.file.excel.easyexcel')
            break
        case 'poi':
            api project(':services.catalog.file.excel.poi')
            break
        default:
            throw new IllegalArgumentException("Unsupported file.excel: ${rootProject.ext.appStack['file.excel']}")
    }
    
    // File::PDF
    switch (rootProject.ext.appStack['file.pdf']) {
        case 'pdfbox':
            api project(':services.catalog.file.pdf.pdfbox')
            break
        default:
            throw new IllegalArgumentException("Unsupported file.pdf: ${rootProject.ext.appStack['file.pdf']}")
    }

    // Full-text search
    switch (rootProject.ext.appStack['full-text-search']) {
        case 'none':
            break
        case 'elasticsearch':
            api project(':services.catalog.full-text-search.elasticsearch')
            break
        default:
            throw new IllegalArgumentException("Unsupported full-text-search: ${rootProject.ext.appStack['full-text-search']}")
    }

    // KV store
    switch (rootProject.ext.appStack['kv-store']) {
        case 'redis':
            api project(':libs.kv-store.redis')
            break
        default:
            throw new IllegalArgumentException("Unsupported kv-store: ${rootProject.ext.appStack['kv-store']}")
    }
    
    // Messaging
    switch (rootProject.ext.appStack['messaging']) {
        case 'kafka':
            api project(':services.catalog.messaging.kafka')
            break
        case 'rabbitmq':
            api project(':services.catalog.messaging.rabbitmq')
            break
        default:
            throw new IllegalArgumentException("Unsupported messaging: ${rootProject.ext.appStack['messaging']}")
    }
    
    // Migration
    switch (rootProject.ext.appStack['migration']) {
        case 'flyway':
            switch (rootProject.ext.appStack['datasource']) {
                case 'mysql':
                    api project(':services.catalog.migration.flyway.mysql')
                    break
                case 'postgres':
                    api project(':services.catalog.migration.flyway.postgres')
                    break
                default:
                    throw new IllegalArgumentException("Unsupported datasource: ${rootProject.ext.appStack['datasource']}")
            }
            break
        default:
            throw new IllegalArgumentException("Unsupported migration: ${rootProject.ext.appStack['migration']}")
    }
    
    // Observability
    switch (rootProject.ext.appStack['observability.logging.framework']) {
        case 'logback':
            api project(':libs.observability.logging.logback')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.logging.framework: ${rootProject.ext.appStack['observability.logging.framework']}")
    }
    switch (rootProject.ext.appStack['observability.metrics']) {
        case 'none':
            break;
        case 'prometheus':
            api project(':libs.observability.metrics.prometheus')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.metrics: ${rootProject.ext.appStack['observability.metrics']}")
    }
    switch (rootProject.ext.appStack['observability.tracing']) {
        case 'none':
            break
        case 'zipkin':
            api project(':libs.observability.tracing.zipkin')
            break
        default:
            throw new IllegalArgumentException("Unsupported observability.tracing: ${rootProject.ext.appStack['observability.tracing']}")
    }
    
    // Outbox
    api project(':libs.outbox')

    // Persistence
    switch (rootProject.ext.appStack.persistence) {
        case 'jpa':
            api project(':services.catalog.persistence.jpa')
            break
        default:
            throw new IllegalArgumentException("Unsupported persistence: ${rootProject.ext.appStack.persistence}")
    }

    // Sequence generator
    api project(':libs.sequence-generator')

    // Service discovery
    switch (rootProject.ext.appStack['service-discovery']) {
        case 'none':
            break
        case 'eureka':
            api project(':libs.discovery-client.eureka')
            break
        case 'kubernetes':
            api project(':libs.discovery-client.kubernetes')
            break
        default:
            throw new IllegalArgumentException("Unsupported service-discovery: ${rootProject.ext.appStack['service-discovery']}")
    }

    // Storage
    switch (rootProject.ext.appStack['storage']) {
        case 'filesystem':
            api project(':libs.storage.filesystem')
            break
        case 'minio':
            api project(':libs.storage.minio')
            break
        default:
            throw new IllegalArgumentException("Unsupported storage: ${rootProject.ext.appStack['storage']}")
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}


idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
