apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
    tier: infrastructure
type: Opaque
data:
  # root
  mysql-username: cm9vdA==
  # root
  mysql-password: cm9vdA==
  mysql-root-password: cm9vdA== 
