plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Schema
    switch (rootProject.ext.appStack['migration']) {
        case 'flyway':
            switch (rootProject.ext.appStack['datasource']) {
                case 'mysql':
                    api project(':libs.outbox.migration.flyway.mysql')
                    break
                case 'postgres':
                    api project(':libs.outbox.migration.flyway.postgres')
                    break
                default:
                    throw new IllegalArgumentException("Unsupported datasource: ${rootProject.ext.appStack['datasource']}")
            }
            break
        default:
            throw new IllegalArgumentException("Unsupported migration: ${rootProject.ext.appStack['migration']}")
    }

    // Persistence
    switch (rootProject.ext.appStack.persistence) {
        case 'jpa':
            api project(':libs.outbox.persistence.jpa')
            break
        default:
            throw new IllegalArgumentException("Unsupported persistence: ${rootProject.ext.appStack.persistence}")
    }

    // Scheduler
    switch (rootProject.ext.appStack['scheduler']) {
        case 'spring':
            api project(':libs.outbox.scheduler.spring')
            break
        case 'quartz':
            api project(':libs.outbox.scheduler.quartz')
            break
        default:
            throw new IllegalArgumentException("Unsupported scheduler: ${rootProject.ext.appStack['scheduler']}")
    }
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
