plugins {
    id 'java-library'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Framework
    api project(':framework')

    // Infrastructure
        switch (rootProject.ext.appStack['api-client']) {
        case 'grpc-netdevh':
            implementation project(':infrastructure.internal-api.auth.grpc.netdevh')
            break
        case 'rest-apachehttpclient':
            implementation project(':infrastructure.internal-api.auth.rest.apachehttpclient')
            break
        case 'rest-feign':
            implementation project(':infrastructure.internal-api.auth.rest.feign')
            break
        case 'rest-restclient':
            implementation project(':infrastructure.internal-api.auth.rest.restclient')
            break
        case 'rest-resttemplate':
            implementation project(':infrastructure.internal-api.auth.rest.resttemplate')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['api-client']}")
    }

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

bootJar {
    enabled = false
}

jar {
    enabled = true
}

test {
    useJUnitPlatform()
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
