apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.payment.fullName }}
  labels:
    app.kubernetes.io/name: {{ .Values.payment.fullName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.global.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.payment.fullName }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.payment.service.rest.port }}
      targetPort: {{ .Values.payment.service.rest.targetPort }}
      name: http
