plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootPluginVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementPluginVersion}"
    id 'idea'
}

group = 'org.atlas'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Domain
    implementation project(':domain.payment')

    // Infrastructure
    switch (rootProject.ext.appStack['api-server']) {
        case 'rest':
            implementation project(':infrastructure.api-server.rest.impl.payment')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['api-server']}")
    }
    switch (rootProject.ext.appStack['cache']) {
        case 'redis':
            implementation project(':infrastructure.cache.redis')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['cache']}")
    }
    switch (rootProject.ext.appStack['datasource']) {
        case 'mysql':
            implementation project(':infrastructure.datasource.mysql.impl.payment')
            break
        case 'postgres':
            implementation project(':infrastructure.datasource.postgres.impl.payment')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['datasource']}")
    }
    switch (rootProject.ext.appStack['discovery-client']) {
        case 'none':
            break
        case 'eureka':
            implementation project(':infrastructure.discovery-client.eureka')
            break
        case 'kubernetes':
            implementation project(':infrastructure.discovery-client.kubernetes')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['discovery-client']}")
    }
    switch (rootProject.ext.appStack['kv']) {
        case 'redis':
            implementation project(':infrastructure.kv.redis.parent')
            break
        case 'dynamodb':
            implementation project(':infrastructure.kv.dynamodb')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['kv']}")
    }
    switch (rootProject.ext.appStack['lock']) {
        case 'redisson':
            implementation project(':infrastructure.lock.redisson')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['lock']}")
    }
    switch (rootProject.ext.appStack['messaging']) {
        case 'kafka':
            implementation project(':infrastructure.messaging.kafka.impl.saga')
            break
        case 'rabbitmq':
            implementation project(':infrastructure.messaging.rabbitmq.impl.saga')
            break
        case 'sns':
            implementation project(':infrastructure.messaging.sns.impl.saga')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['messaging']}")
    }
    switch (rootProject.ext.appStack['migration']) {
        case 'flyway':
            switch (rootProject.ext.appStack['datasource']) {
                case 'mysql':
                    implementation project(':infrastructure.migration.flyway.mysql.impl.payment')
                    break
                case 'postgres':
                    implementation project(':infrastructure.migration.flyway.postgres.impl.payment')
                    break
                default:
                    throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['datasource']}")
            }
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['migration']}")
    }
    implementation project(':infrastructure.observability.actuator')
    switch (rootProject.ext.appStack['observability.logging.framework']) {
        case 'logback':
            implementation project(':infrastructure.observability.logging.logback')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['observability.logging.framework']}")
    }
    switch (rootProject.ext.appStack['observability.metrics']) {
        case 'prometheus':
            implementation project(':infrastructure.observability.metrics.prometheus')
            break
        case 'cloudwatch':
            implementation project(':infrastructure.observability.metrics.cloudwatch')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['observability.metrics']}")
    }
    switch (rootProject.ext.appStack['observability.tracing']) {
        case 'zipkin':
            implementation project(':infrastructure.observability.tracing.zipkin')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['observability.tracing']}")
    }
    implementation project(':infrastructure.payment.parent')
    switch (rootProject.ext.appStack['persistence']) {
        case 'jpa':
            implementation project(':infrastructure.persistence.jpa.impl.payment')
            implementation project(':infrastructure.persistence.jpa.impl.outbox')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['persistence']}")
    }
    switch (rootProject.ext.appStack['scheduler']) {
        case 'spring':
            implementation project(':infrastructure.scheduler.spring.impl.outbox')
            break
        case 'quartz':
            implementation project(':infrastructure.scheduler.quartz.impl.outbox')
            break
        default:
            throw new IllegalArgumentException("Unsupported ${rootProject.ext.appStack['scheduler']}")
    }

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

test {
    useJUnitPlatform()
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
