app:
  auth-client:
    keycloak:
      base-url: ${KEYCLOAK_BASE_URL:http://localhost:8443}
      admin-username: ${KEYCLOAK_ADMIN_USERNAME:atlas}
      admin-password: ${KEYCLOAK_ADMIN_PASSWORD:secret123456}
      realm-name: atlas
      client-id: ${KEYCLOAK_CLIENT_ID:atlas-auth}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:R9RalYMxCvEPv4P47INDfVth9OEY6e52}
