server:
  port: 8901

spring:
  application:
    name: authorization-server
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope:
              # Reference: https://developers.google.com/identity/protocols/oauth2/scopes#oauth2
              - https://www.googleapis.com/auth/userinfo.email
              - https://www.googleapis.com/auth/userinfo.profile
              - openid
      authorizationserver:
        client:
          web-client:
            registration:
              client-id: web-client
              client-authentication-methods:
              # SPA public client cannot safely keep a secret in browser, so use "none" + PKCE
                - none
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - ${OAUTH2_AUTHORIZATION_WEB_CLIENT_REDIRECT_URI:http://localhost:8000/login/callback}
              post-logout-redirect-uris:
                - ${OAUTH2_AUTHORIZATION_WEB_CLIENT_POST_LOGOUT_REDIRECT_URI:http://localhost:8000}
              scopes:
                - openid
                - profile
                - email
                - phone
                - offline_access
            require-proof-key: true
            require-authorization-consent: true

springdoc:
  packages-to-scan: org.atlas.platform.authorization.api

